# Generated by Django 3.1.2 on 2020-11-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_dashboardmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='edad',
            field=models.IntegerField(max_length=10),
        ),
    ]
