# Generated by Django 3.1.2 on 2020-11-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20201109_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
